### ISSUE TITLE
CRUD MongoDb 

### ISSUE THREAD

**Issue by azcotic** [mrdav30/MEANcore#10]
I'm trying to do a CRUD with MongoDB in a clean installment of MEANcore, but I can't find the right spot to put the code, I'm trying in express.js or app.js, but I keep getting errors about mongoose.collectionts or .model arent functions. 

When I look in the module.exports of the mongoose only have three functions implemented, connect, disconnect and loadModels. 

Obviously MEANcore is fine, It is me that I can't find the place or don't understand the project distribution of folders.

**Comment by mrdav30** [comment]
Hi @azcotic,
Documentation is definitely lacking, haven't had the time to focus on it.  MEANcore is set to only load MongoDB schemas that are defined with a ".model.js" prefix.  They can be placed anywhere under the _server_ folder (ex: server/user.server.model.js).

If you did this, are you defining you schema with mongoose, i.e:
`var newSchema = new Schema({
  something: {
    type: String,
    trim: true
  }
}, {
  strict: false
});

mongoose.model('Subscribers', subscribersSchema);`

Once the schema is defined, import mongoose and your model in your controller.  Then you can perform your CRUD operations, i.e.:

`
var mongoose = require('mongoose'),
  NewSchema = mongoose.model('NewSchema');

exports.doSomething = function(req, res) {
  NewSchema.findOne({
    something: req.body.something
}).exec(....
`

**Comment by mrdav30** [comment]
Hi @azcotic, I hope the above resolved your issue.  Since I haven't heard back, I'm closing this as resolved.  Please feel free to reach out if you still have issues.
